// File generated by FlutterFire CLI.
// This file contains Firebase configuration for Daily Glow

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73Ekv8mN3oTvGPEzPGEAFdyGSc44xgo8',
    appId: '1:867927966760:web:3b0d37eabb8e48d501211d',
    messagingSenderId: '867927966760',
    projectId: 'daily-glow-eccbd',
    authDomain: 'daily-glow-eccbd.firebaseapp.com',
    storageBucket: 'daily-glow-eccbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQlKsMOUmqkSsntAIEwe-2Ah4I9K9l-M',
    appId: '1:867927966760:ios:502685906189391b01211d',
    messagingSenderId: '867927966760',
    projectId: 'daily-glow-eccbd',
    storageBucket: 'daily-glow-eccbd.firebasestorage.app',
    iosBundleId: 'com.dailyglow.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7nzLNmuM3YO9O9fAIcQGeYakNS3-4-Y',
    appId: '1:867927966760:android:17a583fdf1885e8b01211d',
    messagingSenderId: '867927966760',
    projectId: 'daily-glow-eccbd',
    storageBucket: 'daily-glow-eccbd.firebasestorage.app',
  );

}